import {test} from 'node:test';
import assert from 'node:assert/strict';
import handler,{discountInput} from '../api/admin-discounts.js';
const id='33333333-3333-4333-8333-333333333333',actor='11111111-1111-4111-8111-111111111111';
const body={code:'CARD5',audience:'public',percentage:5,minimumSubtotal:0,active:true,title:'Launch',startsAt:null,endsAt:'2030-01-01T00:00:00Z'};
const row={id,email:'__PUBLIC__',code:'CARD5',rate:.05,used:false,active:true,title:'Launch',starts_at:null,ends_at:body.endsAt,minimum_subtotal_cents:0,revision:1,created_at:'2026-10-09T00:00:00Z',updated_at:'2026-10-09T00:00:00Z'};
const res=()=>({statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v},status(s){this.statusCode=s;return this},json(body){this.body=body;return this}});
function fixture(t,{email='support@10bottlevalue.co',confirmed=true,result=row,status=200}={}){
 const prev={...process.env};Object.assign(process.env,{SUPABASE_URL:'https://fixture.test',SUPABASE_SERVICE_ROLE_KEY:'private-test',ADMIN_EMAILS:'support@10bottlevalue.co'});delete process.env.ADMIN_USER_IDS;
 t.after(()=>{for(const k of Object.keys(process.env))if(!(k in prev))delete process.env[k];Object.assign(process.env,prev)});
 const calls=[];t.mock.method(globalThis,'fetch',async(url,init={})=>{calls.push({url:new URL(url),init});if(new URL(url).pathname==='/auth/v1/user')return Response.json({id:actor,email,email_confirmed_at:confirmed?'2026-01-01':null,user_metadata:{isAdmin:true}});return Response.json(result,{status});});return calls;
}
test('anonymous, ordinary and unconfirmed users cannot read or edit discounts',async t=>{for(const method of ['GET','POST']){const calls=fixture(t),out=res();await handler({method,headers:{},body},out);assert.equal(out.statusCode,401);assert.equal(calls.length,0);for(const user of [{email:'buyer@example.test'},{confirmed:false}]){const denied=fixture(t,user),r=res();await handler({method,headers:{authorization:'Bearer synthetic'},body},r);assert.equal(r.statusCode,403);assert.equal(denied.length,1)}}});
test('server-authorized edits use the private RPC with captured actor and exact acknowledgement',async t=>{const calls=fixture(t),out=res();await handler({method:'POST',headers:{authorization:'Bearer synthetic'},body:{...body,actorId:'forged',rate:1}},out);assert.equal(out.statusCode,200);assert.equal(out.body.discount.percentage,5);const request=calls[1];assert.equal(request.url.pathname,'/rest/v1/rpc/save_operations_discount');assert.equal(JSON.parse(request.init.body).p_actor_id,actor);assert.equal(JSON.parse(request.init.body).p_rate,.05);assert.equal(request.init.headers.Authorization,'Bearer private-test');assert.doesNotMatch(JSON.stringify(out.body),/private-test|forged/);});
test('missing, changed or suppressed save acknowledgements fail closed',async t=>{for(const result of [null,[],{...row,rate:.1},{...row,title:'lost'},{...row,ends_at:null}]){fixture(t,{result});const out=res();await handler({method:'POST',headers:{authorization:'Bearer synthetic'},body},out);assert.equal(out.statusCode,503)}});
test('optimistic-edit conflicts return a refresh response',async t=>{fixture(t,{status:400,result:{message:'DISCOUNT_REVISION_CONFLICT'}});const out=res();await handler({method:'POST',headers:{authorization:'Bearer synthetic'},body:{...body,id,revision:1}},out);assert.equal(out.statusCode,409);assert.match(out.body.error,/Refresh/);});
test('invalid rates, codes, dates and monetary units never reach storage',()=>{for(const patch of [{percentage:0},{percentage:101},{minimumSubtotal:-1},{minimumSubtotal:.001},{code:'REVIEW10'},{code:'x/y'},{audience:'personal',email:'bad'},{startsAt:'2031-01-01T00:00:00Z'},{endsAt:'2030-01-01T00:00'},{id,revision:null}])assert.throws(()=>discountInput({...body,...patch}));assert.equal(discountInput({...body,minimumSubtotal:12.34}).p_minimum_subtotal_cents,1234);});
test('private list paginates with no-store and rejects invented pages',async t=>{const calls=fixture(t,{result:Array.from({length:101},(_,i)=>({...row,code:`CODE${i}`}))}),out=res();await handler({method:'GET',headers:{authorization:'Bearer synthetic'},query:{page:'1'}},out);assert.equal(out.statusCode,200);assert.equal(out.body.discounts.length,100);assert.equal(out.body.hasMore,true);assert.equal(calls[1].url.searchParams.get('offset'),'100');assert.match(out.headers['Cache-Control'],/no-store/);const bad=res();await handler({method:'GET',headers:{authorization:'Bearer synthetic'},query:{page:'-1'}},bad);assert.equal(bad.statusCode,400);});
