import {test} from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {createLegacyAttemptManager,hostedPaymentUrl} from '../artifacts/10-bottle-value/src/legacy-checkout-attempt.js';
const snapshot={total:347.7,promoCode:'CARD5',email:'buyer@example.test',address:'Example',items:[{name:'Fixture',quantity:1}]};
test('changing provider, network, amount or address gets its own order, and unchanged retry returns the same invoice',async()=>{const m=createLegacyAttemptManager({cryptoApi:webcrypto});m.begin('checkout1','buyer');const first=await m.prepare('catalystpay','lightning',snapshot,'buyer');assert.match(first.orderId,/^INV-[0-9A-F]{32}$/);m.remember(first,'https://verified-provider.example/invoice/one');const again=await m.prepare('catalystpay','lightning',structuredClone(snapshot),'buyer');assert.equal(again,first);assert.equal(again.url,'https://verified-provider.example/invoice/one');for(const [p,s,quote] of [['nowpayments','usdtrx',snapshot],['paylio','paypal',snapshot],['catalystpay','lightning',{...snapshot,total:300}],['catalystpay','lightning',{...snapshot,address:'Changed'}]])assert.notEqual((await m.prepare(p,s,quote,'buyer')).orderId,first.orderId);assert.equal((await m.prepare('catalystpay','lightning',snapshot,'buyer')).orderId,first.orderId);});
test('account changes and signout invalidate stale callbacks and cached contact-associated URLs',async()=>{const m=createLegacyAttemptManager({cryptoApi:webcrypto});m.begin('checkout1','buyer');const a=await m.prepare('paylio','paypal',snapshot,'buyer');m.begin('checkout2','other');await assert.rejects(m.prepare('paylio','paypal',snapshot,'buyer'));assert.throws(()=>m.remember(a,'https://paylio.org/pay/old'));const b=await m.prepare('paylio','paypal',snapshot,'other');assert.notEqual(a.orderId,b.orderId);m.clear();assert.throws(()=>m.remember(b,'https://paylio.org/pay/old'));await assert.rejects(m.prepare('paylio','paypal',snapshot,'other'));});
test('account switches during an asynchronous fingerprint cannot create a stale attempt',async()=>{let release;const cryptoApi={...webcrypto,subtle:{digest:()=>new Promise(resolve=>{release=resolve})},randomUUID:()=>assert.fail('stale request created order')};const m=createLegacyAttemptManager({cryptoApi});m.begin('a','a');const pending=m.prepare('nowpayments','btc',snapshot,'a');m.begin('b','b');release(new ArrayBuffer(32));await assert.rejects(pending,/changed/);});
test('returned navigation URLs require HTTPS and no embedded credentials',()=>{for(const url of ['http://paylio.org/pay/x','javascript:alert(1)','https://name:secret@paylio.org/pay/x','https://paylio.org.evil.test/pay/x'])assert.equal(hostedPaymentUrl(url,'paylio'),null);assert.equal(hostedPaymentUrl('https://nowpayments.io/payment/?iid=123','nowpayments'),'https://nowpayments.io/payment/?iid=123');assert.equal(hostedPaymentUrl('https://evil.test','unknown'),null);});
