// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/account-dashboard/Current.tsx": () => import("../components/mockups/account-dashboard/Current.tsx"),
  "./components/mockups/account-dashboard/Design.tsx": () => import("../components/mockups/account-dashboard/Design.tsx"),
  "./components/mockups/account-dashboard-mobile/Current.tsx": () => import("../components/mockups/account-dashboard-mobile/Current.tsx"),
  "./components/mockups/account-dashboard-mobile/MobileLayoutFix.tsx": () => import("../components/mockups/account-dashboard-mobile/MobileLayoutFix.tsx"),
  "./components/mockups/admin-order-panels/Current.tsx": () => import("../components/mockups/admin-order-panels/Current.tsx"),
  "./components/mockups/admin-order-panels/Outlined.tsx": () => import("../components/mockups/admin-order-panels/Outlined.tsx"),
  "./components/mockups/cart-button/Current.tsx": () => import("../components/mockups/cart-button/Current.tsx"),
  "./components/mockups/cart-button/DarkRed.tsx": () => import("../components/mockups/cart-button/DarkRed.tsx"),
  "./components/mockups/checkout-attestation/CartStyle.tsx": () => import("../components/mockups/checkout-attestation/CartStyle.tsx"),
  "./components/mockups/checkout-attestation/Current.tsx": () => import("../components/mockups/checkout-attestation/Current.tsx"),
  "./components/mockups/footer-legal/Current.tsx": () => import("../components/mockups/footer-legal/Current.tsx"),
  "./components/mockups/footer-legal/TwoColumn.tsx": () => import("../components/mockups/footer-legal/TwoColumn.tsx"),
  "./components/mockups/product-info-button/Current.tsx": () => import("../components/mockups/product-info-button/Current.tsx"),
  "./components/mockups/product-info-button/MoreVisible.tsx": () => import("../components/mockups/product-info-button/MoreVisible.tsx"),
  "./components/mockups/signup-verification/Current.tsx": () => import("../components/mockups/signup-verification/Current.tsx"),
  "./components/mockups/signup-verification/Refined.tsx": () => import("../components/mockups/signup-verification/Refined.tsx")
};
