// Server-side source of truth for product catalog (prices & stock).
// This MUST be kept in sync with PRODUCTS_BASE in artifacts/10bottle/src/App.jsx.
// It exists so create-stripe-session.js never has to trust prices/stock
// submitted by the client — those can be freely manipulated in the browser.

// CATALOG_DATA_START — auto-generated by sync-catalog.mjs from product-catalog.json.
// Do not hand-edit this array; edit product-catalog.json and re-run sync-catalog.mjs
// (or just ask the agent to update a product) so this file and App.jsx stay in sync.
const PRODUCTS = [
  { "name": "BPC-157", "dose": "10 mg", "price": 139 },
  { "name": "BPC-157", "dose": "10 mg", "price": 179, "usPriceBase": 174, "warehouse": "us" },
  { "name": "BPC-157", "dose": "5 mg", "price": 79 },
  { "name": "TB-500", "dose": "10 mg", "price": 219 },
  { "name": "TB-500", "dose": "5 mg", "price": 149 },
  { "name": "TB-500 + BPC-157", "dose": "10 mg", "price": 169 },
  { "name": "TB-500 + BPC-157", "dose": "10 mg", "price": 169, "usPriceBase": 204, "warehouse": "us" },
  { "name": "TB-500 + BPC-157", "dose": "20 mg", "price": 299 },
  { "name": "TB-500 + BPC-157", "dose": "20 mg", "price": 299, "usPriceBase": 314, "warehouse": "us" },
  { "name": "Ipamorelin", "dose": "10 mg", "price": 159 },
  { "name": "Ipamorelin", "dose": "5 mg", "price": 89 },
  { "name": "Ipamorelin", "dose": "5 mg", "price": 89, "usPriceBase": 140, "warehouse": "us" },
  { "name": "Tirzepatide / GLP-2", "dose": "5 mg", "price": 79 },
  { "name": "Tirzepatide / GLP-2", "dose": "10 mg", "price": 99 },
  { "name": "Tirzepatide / GLP-2", "dose": "10 mg", "price": 99, "usPriceBase": 144, "warehouse": "us" },
  { "name": "Tirzepatide / GLP-2", "dose": "15 mg", "price": 129 },
  { "name": "Tirzepatide / GLP-2", "dose": "20 mg", "price": 149 },
  { "name": "Sermorelin", "dose": "10 mg", "price": 239 },
  { "name": "Sermorelin", "dose": "5 mg", "price": 139, "outOfStock": true },
  { "name": "Tesamorelin", "dose": "5 mg", "price": 219 },
  { "name": "Tesamorelin", "dose": "10 mg", "price": 339 },
  { "name": "Tesamorelin", "dose": "10 mg", "price": 339, "usPriceBase": 334, "warehouse": "us" },
  { "name": "IGF-1 LR3", "dose": "1 mg", "price": 375 },
  { "name": "IGF-1 LR3", "dose": "0.1 mg", "price": 79 },
  { "name": "Retatrutide / GLP-3", "dose": "5 mg", "price": 109 },
  { "name": "Retatrutide / GLP-3", "dose": "5 mg", "price": 109, "usPriceBase": 154, "warehouse": "us" },
  { "name": "Retatrutide / GLP-3", "dose": "10 mg", "price": 159 },
  { "name": "Retatrutide / GLP-3", "dose": "10 mg", "price": 159, "usPriceBase": 194, "warehouse": "us" },
  { "name": "Retatrutide / GLP-3", "dose": "15 mg", "price": 209 },
  { "name": "Retatrutide / GLP-3", "dose": "20 mg", "price": 259 },
  { "name": "Retatrutide / GLP-3", "dose": "20 mg", "price": 259, "usPriceBase": 280, "warehouse": "us" },
  { "name": "Retatrutide / GLP-3", "dose": "30 mg", "price": 339 },
  { "name": "Retatrutide / GLP-3", "dose": "30 mg", "price": 339, "usPriceBase": 364, "warehouse": "us" },
  { "name": "Retatrutide / GLP-3", "dose": "40 mg", "price": 419 },
  { "name": "Retatrutide / GLP-3", "dose": "40 mg", "price": 419, "usPriceBase": 444, "warehouse": "us" },
  { "name": "Retatrutide / GLP-3", "dose": "50 mg", "price": 509 },
  { "name": "Retatrutide / GLP-3", "dose": "50 mg", "price": 509, "usPriceBase": 514, "warehouse": "us" },
  { "name": "Retatrutide / GLP-3", "dose": "60 mg", "price": 579 },
  { "name": "Mazdutide", "dose": "10 mg", "price": 389 },
  { "name": "Tirzepatide / GLP-2", "dose": "30 mg", "price": 189 },
  { "name": "Tirzepatide / GLP-2", "dose": "30 mg", "price": 189, "usPriceBase": 224, "warehouse": "us" },
  { "name": "Tirzepatide / GLP-2", "dose": "40 mg", "price": 229 },
  { "name": "Tirzepatide / GLP-2", "dose": "40 mg", "price": 229, "usPriceBase": 260, "warehouse": "us" },
  { "name": "Tirzepatide / GLP-2", "dose": "50 mg", "price": 289 },
  { "name": "Tirzepatide / GLP-2", "dose": "60 mg", "price": 339 },
  { "name": "Tirzepatide / GLP-2", "dose": "60 mg", "price": 339, "usPriceBase": 344, "warehouse": "us" },
  { "name": "Semax", "dose": "10 mg", "price": 109 },
  { "name": "Semax", "dose": "10 mg", "price": 99, "usPriceBase": 144, "warehouse": "us" },
  { "name": "Semax", "dose": "5 mg", "price": 79 },
  { "name": "Selank", "dose": "5 mg", "price": 79 },
  { "name": "Selank", "dose": "10 mg", "price": 109 },
  { "name": "Selank", "dose": "10 mg", "price": 99, "usPriceBase": 144, "warehouse": "us" },
  { "name": "DSIP", "dose": "15 mg", "price": 169 },
  { "name": "DSIP", "dose": "5 mg", "price": 89 },
  { "name": "GHK-CU", "dose": "100 mg", "price": 99 },
  { "name": "GHK-CU", "dose": "50 mg", "price": 89, "usPriceBase": 114, "warehouse": "us" },
  { "name": "GHK-CU", "dose": "100 mg", "price": 165, "usPriceBase": 160, "warehouse": "us" },
  { "name": "Glutathione", "dose": "600 mg", "price": 139 },
  { "name": "Glutathione", "dose": "1500 mg", "price": 179 },
  { "name": "NAD+", "dose": "1000 mg", "price": 259 },
  { "name": "NAD+", "dose": "500 mg", "price": 159 },
  { "name": "SS-31", "dose": "50 mg", "price": 569 },
  { "name": "SS-31", "dose": "10 mg", "price": 169 },
  { "name": "KPV", "dose": "10 mg", "price": 119 },
  { "name": "KPV", "dose": "10 mg", "price": 119, "usPriceBase": 164, "warehouse": "us" },
  { "name": "MOTS-C", "dose": "40 mg", "price": 369 },
  { "name": "MOTS-C", "dose": "10 mg", "price": 129 },
  { "name": "MOTS-C", "dose": "10 mg", "price": 129, "usPriceBase": 174, "warehouse": "us" },
  { "name": "Thymosin Alpha-1", "dose": "10 mg", "price": 289 },
  { "name": "Melanotan-2", "dose": "10 mg", "price": 89 },
  { "name": "SNAP-8", "dose": "10 mg", "price": 79 },
  { "name": "KLOW80", "dose": "80 mg", "price": 379 },
  { "name": "KLOW80", "dose": "80 mg", "price": 389, "usPriceBase": 384, "warehouse": "us" },
  { "name": "BAC Water", "dose": "10 ml", "price": 29, "outOfStock": true },
  { "name": "BAC Water", "dose": "3 ml", "price": 19 },
  { "name": "Semaglutide", "dose": "5 mg", "price": 69 },
  { "name": "Semaglutide", "dose": "10 mg", "price": 89 },
  { "name": "Semaglutide", "dose": "15 mg", "price": 119 },
  { "name": "Semaglutide", "dose": "20 mg", "price": 139 },
  { "name": "Semaglutide", "dose": "30 mg", "price": 179 },
  { "name": "PT-141", "dose": "10 mg", "price": 119 },
  { "name": "Cagrilintide", "dose": "5 mg", "price": 209 },
  { "name": "Cagrilintide", "dose": "10 mg", "price": 369 },
  { "name": "Cagrilintide + Semaglutide", "dose": "10 mg each", "price": 379 },
  { "name": "CJC-1295 + Ipamorelin", "dose": "10 mg each", "price": 189, "noteLabel": "no/d" },
  { "name": "CJC-1295 + Ipamorelin", "dose": "10 mg each", "price": 249, "usPriceBase": 244, "noteLabel": "no/d", "warehouse": "us" },
  { "name": "CJC-1295", "dose": "5 mg", "price": 319, "noteLabel": "with/d" },
  { "name": "CJC-1295", "dose": "5 mg", "price": 169, "noteLabel": "no/d" },
  { "name": "CJC-1295", "dose": "10 mg", "price": 299, "noteLabel": "no/d" },
  { "name": "Survodutide", "dose": "10 mg", "price": 539 },
  { "name": "AHK-CU", "dose": "100 mg", "price": 89 },
  { "name": "AOD", "dose": "5 mg", "price": 209 },
  { "name": "AOD", "dose": "5 mg", "price": 209, "usPriceBase": 244, "warehouse": "us" },
  { "name": "IGF-DES", "dose": "2 mg", "price": 109, "outOfStock": true },
  { "name": "GHRP-2", "dose": "5 mg", "price": 89 },
  { "name": "GHRP-2", "dose": "10 mg", "price": 139 },
  { "name": "GHRP-6", "dose": "5 mg", "price": 139 },
  { "name": "GHRP-6", "dose": "10 mg", "price": 187 },
  { "name": "HCG", "dose": "5000 iu", "price": 169 },
  { "name": "HCG", "dose": "5000 iu", "price": 169, "usPriceBase": 204, "warehouse": "us" },
  { "name": "HCG", "dose": "10000 iu", "price": 319 },
  { "name": "HCG", "dose": "10000 iu", "price": 335, "usPriceBase": 330, "warehouse": "us" },
  { "name": "HMG", "dose": "75 iu", "price": 119 },
  { "name": "Oxytocin", "dose": "2 mg", "price": 49 },
  { "name": "Epitalon", "dose": "10 mg", "price": 95 },
  { "name": "Epitalon", "dose": "10 mg", "price": 95, "usPriceBase": 144, "warehouse": "us" },
  { "name": "Epitalon", "dose": "50 mg", "price": 299 },
  { "name": "Cartalax", "dose": "20 mg", "price": 199 },
  { "name": "Eloralintide", "dose": "5 mg", "price": 329 },
  { "name": "Eloralintide", "dose": "10 mg", "price": 469 },
  { "name": "AICAR", "dose": "50 mg", "price": 123 },
  { "name": "ARA290 (Cibinetide)", "dose": "10 mg", "price": 159 },
  { "name": "Adipotide", "dose": "2 mg", "price": 139 },
  { "name": "Adipotide", "dose": "5 mg", "price": 299 },
  { "name": "KissPeptin-10", "dose": "5 mg", "price": 99 },
  { "name": "KissPeptin-10", "dose": "10 mg", "price": 169 },
  { "name": "Thymosin Alpha-1", "dose": "5 mg", "price": 159 },
  { "name": "LL37", "dose": "5 mg", "price": 189 },
  { "name": "Melatonin", "dose": "10 mg", "price": 109 },
  { "name": "NAD+", "dose": "100 mg", "price": 79 },
  { "name": "5-Amino-1MQ", "dose": "5 mg", "price": 89 },
  { "name": "5-Amino-1MQ", "dose": "5 mg", "price": 89, "usPriceBase": 140, "warehouse": "us", "outOfStock": true },
  { "name": "5-Amino-1MQ", "dose": "10 mg", "price": 119 },
  { "name": "Lipo-C (with B12)", "dose": "10 ml", "price": 149 },
  { "name": "L-Carnitine (600mg/ml)", "dose": "10 ml", "price": 159 },
  { "name": "Pinealon", "dose": "5 mg", "price": 109, "outOfStock": true },
  { "name": "Pinealon", "dose": "10 mg", "price": 139 },
  { "name": "Pinealon", "dose": "20 mg", "price": 199 },
  { "name": "Lemon Bottle", "dose": "10 ml", "price": 199 },
  { "name": "SLU-PP-332", "dose": "5 mg", "price": 199 },
  { "name": "Triptorelin", "dose": "2 mg", "price": 99 },
  { "name": "PEG-MGF", "dose": "2 mg", "price": 159 },
  { "name": "MGF", "dose": "2 mg", "price": 99 },
  { "name": "GDF-8", "dose": "1 mg", "price": 339 },
  { "name": "FOXO4-DRI", "dose": "10 mg", "price": 559 },
  { "name": "VIP", "dose": "5 mg", "price": 165 },
  { "name": "VIP", "dose": "10 mg", "price": 329 },
  { "name": "ACE-031", "dose": "1 mg", "price": 379 },
  { "name": "Gonadorelin", "dose": "2 mg", "price": 65 },
  { "name": "Hexarelin Acetate", "dose": "2 mg", "price": 119 },
  { "name": "Hexarelin Acetate", "dose": "5 mg", "price": 219 },
  { "name": "PNC-27", "dose": "5 mg", "price": 239 },
  { "name": "PNC-27", "dose": "10 mg", "price": 399 },
];
// CATALOG_DATA_END

function normalize(value) {
  return String(value || "").trim().toLowerCase();
}

// Normalize a dose string: strip spaces between number and unit so
// "20mg" and "20 mg" both become "20mg" for comparison.
function normalizeDose(value) {
  return normalize(value).replace(/(\d)\s+([a-z])/g, "$1$2");
}

// Compare product names flexibly:
//   - exact match: "Retatrutide / GLP-3" === "Retatrutide / GLP-3"
//   - prefix match: "Retatrutide / GLP-3" matches client sending just "Retatrutide"
//     (handles old localStorage cart entries that pre-date the "/ GLP-X" rename)
function namesMatch(catalogName, clientName) {
  const cat = normalize(catalogName);
  const cli = normalize(clientName);
  if (cat === cli) return true;
  // If client sent the base name before " / ", accept it
  const base = cat.split(" / ")[0].trim();
  return base === cli;
}

// Mirrors getProductId() in App.jsx (name + noteLabel + dose [+ warehouse]).
// Warehouse check is symmetric: US items only match US requests and vice-versa,
// so a client that omits fromWarehouse cannot inadvertently match a US-only SKU
// (which would break routing and pricing).
function findCatalogProduct({ name, dose, noteLabel, fromWarehouse }) {
  const wantsUs = fromWarehouse === "us";
  const exact = PRODUCTS.find(
    (p) =>
      namesMatch(p.name, name) &&
      normalizeDose(p.dose) === normalizeDose(dose) &&
      normalize(p.noteLabel) === normalize(noteLabel) &&
      (p.warehouse === "us") === wantsUs
  );
  if (exact) return exact;
  // Some SKUs only exist as a US-warehouse catalog entry (no separate
  // worldwide entry), but the same product/dose is also sold from the
  // regular "Shop Worldwide" catalog at the non-US price. If the client
  // didn't request US warehouse, fall back to that us-flagged entry so
  // checkout still succeeds — just priced/shipped as a regular item.
  if (!wantsUs) {
    return (
      PRODUCTS.find(
        (p) =>
          namesMatch(p.name, name) &&
          normalizeDose(p.dose) === normalizeDose(dose) &&
          normalize(p.noteLabel) === normalize(noteLabel)
      ) || null
    );
  }
  return null;
}

// Mirrors the US-warehouse pricing formula used in App.jsx:
// price = (usPriceBase ?? price) + 5  (no discount)
function getUnitPrice(catalogProduct, fromWarehouse) {
  if (fromWarehouse === "us") {
    return (catalogProduct.usPriceBase ?? catalogProduct.price) + 5;
  }
  return catalogProduct.price;
}

// Mirrors getShippingPrice() in App.jsx.
function getShippingPrice(subtotal, type) {
  if (type === "express") {
    if (subtotal >= 550) return 0;
    if (subtotal >= 300) return 39.99;
    return 99.99;
  }
  if (subtotal >= 300) return 0;
  if (subtotal >= 100) return 49.99;
  return 59.99;
}

// Mirrors automaticDiscountRate tiers in App.jsx.
function getAutomaticDiscountRate(subtotal) {
  if (subtotal >= 4000) return 0.2;
  if (subtotal >= 2000) return 0.15;
  if (subtotal >= 1000) return 0.1;
  return 0;
}

// Validates & re-prices a cart against the server catalog.
// Throws an Error with a user-safe message if anything is invalid.
function validateAndPriceItems(items) {
  if (!Array.isArray(items) || items.length === 0) {
    throw new Error("Cart is empty or invalid.");
  }

  const pricedItems = [];
  let regularSubtotal = 0;
  let usSubtotal = 0;

  for (const rawItem of items) {
    const quantity = Number(rawItem?.quantity);
    if (!Number.isInteger(quantity) || quantity < 1 || quantity > 50) {
      throw new Error(`Invalid quantity for item: ${rawItem?.name || "unknown"}`);
    }

    const fromWarehouse = rawItem?.fromWarehouse === "us" ? "us" : undefined;
    const catalogProduct = findCatalogProduct({
      name: rawItem?.name,
      dose: rawItem?.dose,
      noteLabel: rawItem?.noteLabel,
      fromWarehouse,
    });

    if (!catalogProduct) {
      throw new Error(`Unknown product: ${rawItem?.name || "?"} ${rawItem?.dose || ""}`);
    }
    if (catalogProduct.outOfStock) {
      throw new Error(`Product is out of stock: ${catalogProduct.name} ${catalogProduct.dose}`);
    }

    const unitPrice = getUnitPrice(catalogProduct, fromWarehouse);
    const lineTotal = Math.round(unitPrice * quantity * 100) / 100;

    if (fromWarehouse === "us") {
      usSubtotal += lineTotal;
    } else {
      regularSubtotal += lineTotal;
    }

    pricedItems.push({
      name: catalogProduct.name,
      dose: catalogProduct.dose,
      quantity,
      price: unitPrice,
      ...(fromWarehouse ? { fromWarehouse } : {}),
    });
  }

  regularSubtotal = Math.round(regularSubtotal * 100) / 100;
  usSubtotal = Math.round(usSubtotal * 100) / 100;
  const subtotal = Math.round((regularSubtotal + usSubtotal) * 100) / 100;

  return { pricedItems, subtotal, regularSubtotal, usSubtotal };
}

export {
  PRODUCTS,
  findCatalogProduct,
  getUnitPrice,
  getShippingPrice,
  getAutomaticDiscountRate,
  validateAndPriceItems,
};
